#! /usr/bin/env php

<?php

/**
 * Load correct autoloader depending on install location.
 */
// if (file_exists(__DIR__.'/vendor/autoload.php')) {
//     require __DIR__.'/vendor/autoload.php';
// } else {
//     require __DIR__.'/../../autoload.php';
// }

use Studio\NewCommand;
use Symfony\Component\Console\Application;

$app = new Application('Studio Installer', '1.0.0');

$app->add(new NewCommand(new GuzzleHttp\Client()));

$app->run();
